### ISSUE TITLE
cron.weekly is not active anymore

### ISSUE THREAD

**Issue by fedepell** [webpro/awesome-newsletters#25]
Hi,
Sadly cron.weekly is not really active anymore, even tho a "comeback" is announced, maybe you want to put it under "halted newsletters".

From cron.weekly webiste:

> Heads-up! cron.weekly is taking a break. issue #112 was the last issue to be sent. Expect a return in a few months or so, feel free to keep subscribing! 

Cheers,
F.

**Comment by webpro** [comment]
Thanks, @fedepell!
