### ISSUE TITLE
alphabetical & seperate JavaScript-esqe?

### ISSUE THREAD

**Issue by tomByrer** [webpro/awesome-newsletters#3]
IMHO there are too many entries not to be alphabetical.

I think JavaScript should be separated out, since there is [ES.next News](http://us12.campaign-archive2.com/?u=d3a2c4d93441c84c0a1e6e808&id=dc2995453d&e=355263ad97), 3 TypeScript newsletters, etc.  Up to you if you want to merge Node in, but I think it should be merged since there is much crossover.

Assuming you want other newsletters for other languages (Go, SQL, etc)?

**Comment by webpro** [comment]
The order is based on the date of the first issue (6th column), oldest first.

Other than that, I agree it's perhaps better to have a "JavaScript" (including Node.js) section, and maybe a generic "Frontend" section (CSS, Smashing Mag).

And sure, other topics are welcome, too!

**Comment by tomByrer** [comment]
Cool!

For some of the newsletters, it is hard to tell when started since they don't have all backissues archived.

**Comment by webpro** [comment]
Date of 1st issue isn't required, or doesn't need to be linked to if not available.

Also, I'm open to a more readable table. Ideas:

* Combined archive + rss column
* Combined curator + publisher (+ twitter) column
* Abbreviated day
* ...

Not sure if there are any options e.g. to (un)fold things within a table.

**Comment by webpro** [comment]
I think this can be closed now.
